// automatically generated by the FlatBuffers compiler, do not modify

package jvm_toolbox_flatbuffers.inspector;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class JavaObject extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_5_9(); }
  public static JavaObject getRootAsJavaObject(ByteBuffer _bb) { return getRootAsJavaObject(_bb, new JavaObject()); }
  public static JavaObject getRootAsJavaObject(ByteBuffer _bb, JavaObject obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public JavaObject __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long address() { int o = __offset(4); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public int size() { int o = __offset(6); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public int hashCode() { int o = __offset(8); return o != 0 ? bb.getInt(o + bb_pos) : 0; }

  public static int createJavaObject(FlatBufferBuilder builder,
      long address,
      int size,
      int hashCode) {
    builder.startTable(3);
    JavaObject.addAddress(builder, address);
    JavaObject.addHashCode(builder, hashCode);
    JavaObject.addSize(builder, size);
    return JavaObject.endJavaObject(builder);
  }

  public static void startJavaObject(FlatBufferBuilder builder) { builder.startTable(3); }
  public static void addAddress(FlatBufferBuilder builder, long address) { builder.addLong(0, address, 0L); }
  public static void addSize(FlatBufferBuilder builder, int size) { builder.addInt(1, size, 0); }
  public static void addHashCode(FlatBufferBuilder builder, int hashCode) { builder.addInt(2, hashCode, 0); }
  public static int endJavaObject(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public JavaObject get(int j) { return get(new JavaObject(), j); }
    public JavaObject get(JavaObject obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

