// automatically generated by the FlatBuffers compiler, do not modify

package jvm_toolbox_flatbuffers.inspector;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class JavaThread extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_5_9(); }
  public static JavaThread getRootAsJavaThread(ByteBuffer _bb) { return getRootAsJavaThread(_bb, new JavaThread()); }
  public static JavaThread getRootAsJavaThread(ByteBuffer _bb, JavaThread obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public JavaThread __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int state() { int o = __offset(4); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public String name() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer nameAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer nameInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }
  public int priority() { int o = __offset(8); return o != 0 ? bb.getInt(o + bb_pos) : 0; }
  public boolean isDaemon() { int o = __offset(10); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }

  public static int createJavaThread(FlatBufferBuilder builder,
      int state,
      int nameOffset,
      int priority,
      boolean isDaemon) {
    builder.startTable(4);
    JavaThread.addPriority(builder, priority);
    JavaThread.addName(builder, nameOffset);
    JavaThread.addState(builder, state);
    JavaThread.addIsDaemon(builder, isDaemon);
    return JavaThread.endJavaThread(builder);
  }

  public static void startJavaThread(FlatBufferBuilder builder) { builder.startTable(4); }
  public static void addState(FlatBufferBuilder builder, int state) { builder.addInt(0, state, 0); }
  public static void addName(FlatBufferBuilder builder, int nameOffset) { builder.addOffset(1, nameOffset, 0); }
  public static void addPriority(FlatBufferBuilder builder, int priority) { builder.addInt(2, priority, 0); }
  public static void addIsDaemon(FlatBufferBuilder builder, boolean isDaemon) { builder.addBoolean(3, isDaemon, false); }
  public static int endJavaThread(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public JavaThread get(int j) { return get(new JavaThread(), j); }
    public JavaThread get(JavaThread obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

