// automatically generated by the FlatBuffers compiler, do not modify

package jvm_toolbox_flatbuffers.inspector;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class OnFieldModification extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_5_9(); }
  public static OnFieldModification getRootAsOnFieldModification(ByteBuffer _bb) { return getRootAsOnFieldModification(_bb, new OnFieldModification()); }
  public static OnFieldModification getRootAsOnFieldModification(ByteBuffer _bb, OnFieldModification obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public OnFieldModification __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public jvm_toolbox_flatbuffers.inspector.JavaThread thread() { return thread(new jvm_toolbox_flatbuffers.inspector.JavaThread()); }
  public jvm_toolbox_flatbuffers.inspector.JavaThread thread(jvm_toolbox_flatbuffers.inspector.JavaThread obj) { int o = __offset(4); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public jvm_toolbox_flatbuffers.inspector.JavaMethod method() { return method(new jvm_toolbox_flatbuffers.inspector.JavaMethod()); }
  public jvm_toolbox_flatbuffers.inspector.JavaMethod method(jvm_toolbox_flatbuffers.inspector.JavaMethod obj) { int o = __offset(6); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public long location() { int o = __offset(8); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }
  public jvm_toolbox_flatbuffers.inspector.JavaClass class_() { return class_(new jvm_toolbox_flatbuffers.inspector.JavaClass()); }
  public jvm_toolbox_flatbuffers.inspector.JavaClass class_(jvm_toolbox_flatbuffers.inspector.JavaClass obj) { int o = __offset(10); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public jvm_toolbox_flatbuffers.inspector.JavaObject object() { return object(new jvm_toolbox_flatbuffers.inspector.JavaObject()); }
  public jvm_toolbox_flatbuffers.inspector.JavaObject object(jvm_toolbox_flatbuffers.inspector.JavaObject obj) { int o = __offset(12); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public jvm_toolbox_flatbuffers.inspector.JavaField field() { return field(new jvm_toolbox_flatbuffers.inspector.JavaField()); }
  public jvm_toolbox_flatbuffers.inspector.JavaField field(jvm_toolbox_flatbuffers.inspector.JavaField obj) { int o = __offset(14); return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null; }
  public byte signatureType() { int o = __offset(16); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public long newValue() { int o = __offset(18); return o != 0 ? bb.getLong(o + bb_pos) : 0L; }

  public static int createOnFieldModification(FlatBufferBuilder builder,
      int threadOffset,
      int methodOffset,
      long location,
      int class_Offset,
      int objectOffset,
      int fieldOffset,
      byte signatureType,
      long newValue) {
    builder.startTable(8);
    OnFieldModification.addNewValue(builder, newValue);
    OnFieldModification.addLocation(builder, location);
    OnFieldModification.addField(builder, fieldOffset);
    OnFieldModification.addObject(builder, objectOffset);
    OnFieldModification.addClass(builder, class_Offset);
    OnFieldModification.addMethod(builder, methodOffset);
    OnFieldModification.addThread(builder, threadOffset);
    OnFieldModification.addSignatureType(builder, signatureType);
    return OnFieldModification.endOnFieldModification(builder);
  }

  public static void startOnFieldModification(FlatBufferBuilder builder) { builder.startTable(8); }
  public static void addThread(FlatBufferBuilder builder, int threadOffset) { builder.addOffset(0, threadOffset, 0); }
  public static void addMethod(FlatBufferBuilder builder, int methodOffset) { builder.addOffset(1, methodOffset, 0); }
  public static void addLocation(FlatBufferBuilder builder, long location) { builder.addLong(2, location, 0L); }
  public static void addClass(FlatBufferBuilder builder, int class_Offset) { builder.addOffset(3, class_Offset, 0); }
  public static void addObject(FlatBufferBuilder builder, int objectOffset) { builder.addOffset(4, objectOffset, 0); }
  public static void addField(FlatBufferBuilder builder, int fieldOffset) { builder.addOffset(5, fieldOffset, 0); }
  public static void addSignatureType(FlatBufferBuilder builder, byte signatureType) { builder.addByte(6, signatureType, 0); }
  public static void addNewValue(FlatBufferBuilder builder, long newValue) { builder.addLong(7, newValue, 0L); }
  public static int endOnFieldModification(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public OnFieldModification get(int j) { return get(new OnFieldModification(), j); }
    public OnFieldModification get(OnFieldModification obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

