// automatically generated by the FlatBuffers compiler, do not modify

package jvm_toolbox_flatbuffers.inspector;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class OnInspectorLoaded extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_5_9(); }
  public static OnInspectorLoaded getRootAsOnInspectorLoaded(ByteBuffer _bb) { return getRootAsOnInspectorLoaded(_bb, new OnInspectorLoaded()); }
  public static OnInspectorLoaded getRootAsOnInspectorLoaded(ByteBuffer _bb, OnInspectorLoaded obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public OnInspectorLoaded __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String inspectorInterface() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer inspectorInterfaceAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer inspectorInterfaceInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }

  public static int createOnInspectorLoaded(FlatBufferBuilder builder,
      int inspectorInterfaceOffset) {
    builder.startTable(1);
    OnInspectorLoaded.addInspectorInterface(builder, inspectorInterfaceOffset);
    return OnInspectorLoaded.endOnInspectorLoaded(builder);
  }

  public static void startOnInspectorLoaded(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addInspectorInterface(FlatBufferBuilder builder, int inspectorInterfaceOffset) { builder.addOffset(0, inspectorInterfaceOffset, 0); }
  public static int endOnInspectorLoaded(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public OnInspectorLoaded get(int j) { return get(new OnInspectorLoaded(), j); }
    public OnInspectorLoaded get(OnInspectorLoaded obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

