// automatically generated by the FlatBuffers compiler, do not modify

package jvm_toolbox_flatbuffers.inspector;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class OnVMDeath extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_5_9(); }
  public static OnVMDeath getRootAsOnVMDeath(ByteBuffer _bb) { return getRootAsOnVMDeath(_bb, new OnVMDeath()); }
  public static OnVMDeath getRootAsOnVMDeath(ByteBuffer _bb, OnVMDeath obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public OnVMDeath __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void startOnVMDeath(FlatBufferBuilder builder) { builder.startTable(0); }
  public static int endOnVMDeath(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public OnVMDeath get(int j) { return get(new OnVMDeath(), j); }
    public OnVMDeath get(OnVMDeath obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

